### ISSUE TITLE
Creating migrations table fails in version 1.6.0

### ISSUE THREAD

**Issue by jackbutler** [db-migrate/db-migrate-base#14]
I'm seeing the following error since upgrading to version 1.6.0, at the point of db-migrate creating the migrations table:

```
[ERROR] TypeError: Cannot read property 'raw' of undefined
    at Object._prepareSpec (/usr/lib/node_modules/db-migrate-pg/node_modules/db-migrate-base/index.js:46:26)
    at Object.createTable (/usr/lib/node_modules/db-migrate-pg/node_modules/db-migrate-base/index.js:258:12)
    at /usr/lib/node_modules/db-migrate/lib/driver/shadow.js:34:50
    at tryCatcher (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/db-migrate/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Edit**
This is being installed as dependencies of the following:
`db-migrate@0.11.1 db-migrate-pg@0.4.0`

**Comment by wzrdtales** [comment]
@jackbutler Can you try to update again?

**Comment by wzrdtales** [comment]
Tested version 0.4.0 locallly, it is working again with base 1.6.3, need to add a shrinkwrap to the pg driver. thank you for reporting! Feel free to post again shouldn't this be fixed for you.
